# Generated by Django 2.1.5 on 2020-09-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCursos', '0003_auto_20200821_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
            ],
        ),
    ]
