# Generated by Django 2.1.5 on 2020-09-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCursos', '0006_auto_20200912_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='asistido',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
